const urls = {
    "ACCOUNT_DETAILS": "cloudfabric.cisco.com/v1/cloudaccounts",
    "DELETE_RECORD": "cloudfabric.cisco.com/v1/cloudaccounts/",
    "GET_CALL_STACK": "cloudfabric.cisco.com/v1/cloudformations/",
    "ADD_AWS_ACCOUNTS":"cloudfabric.cisco.com/v1/cloudformations",
    "CLOUD_RESOURCES": "cloudfabric.cisco.com/v1/vpcs",
    "GCP_VPCS": "cloudfabric.cisco.com/v1/gcpvpcs",
    "AZ_VPCS": "cloudfabric.cisco.com/v1/azvpcs",
    "AWS_VPCS": "cloudfabric.cisco.com/v1/awsvpcs",
    "CLOUD_REGIONS": "cloudfabric.cisco.com/v1/regions",
    "CLOUD_REGIONS_PROVIDERNAME": "cloudfabric.cisco.com/v1/regions/specName/qui/specProviderName/",
    "ENDPOINTS_AWS": "cloudfabric.cisco.com/v1/awsnicopers",
    "ENDPOINTS_AZURE": "cloudfabric.cisco.com/v1/aznicopers",
    "ENDPOINTS_GCP": "cloudfabric.cisco.com/v1/gcpnicopers",
    "KUBERNETS_AWS": "cloudfabric.cisco.com/v1/awseksclusteropers",
    "KUBERNETS_AZURE": "cloudfabric.cisco.com/v1/azk8sclusteropers",
    "KUBERNETS_GCP": "cloudfabric.cisco.com/v1/gcpgkeclusteropers",
    "INSTANCESVMS_AWS" : "cloudfabric.cisco.com/v1/awsinstanceopers",
    "INSTANCESVMS_AZURE" : "cloudfabric.cisco.com/v1/azvmopers",
    "INSTANCESVMS_GCP" : "cloudfabric.cisco.com/v1/gcpinstanceopers",
    "SECURITYGROUPS_AWS":"cloudfabric.cisco.com/v1/awssgopers",
    "SECURITYGROUPS_AZURE":"cloudfabric.cisco.com/v1/azsgopers",
    "SUBNETS": "cloudfabric.cisco.com/v1/subnets",
    "SUBNETS_AWS": "cloudfabric.cisco.com/v1/awssubnets",
    "SUBNETS_AZ": "cloudfabric.cisco.com/v1/azsubnets",
    "ROUTE_TABLES":"cloudfabric.cisco.com/v1/routetables",
    "ROUTE_TABLES_GCP":"cloudfabric.cisco.com/v1/gcprouteopers",
    "ROUTE_TABLES_AWS":"cloudfabric.cisco.com/v1/awsroutetables",
    "ROUTE_TABLES_AZ":"cloudfabric.cisco.com/v1/azroutetables",
    "NETWORKS":"cloudfabric.cisco.com/v1/networks",
    "ADD_NETWORKS": "cloudfabric.cisco.com/v1/namespaces/default/networks"
}

export default urls;
